---
fullname: Hoare Logic for Coinductive Trace-Based Semantics of While
shortname: coind-sem-while
opam_name: coq-coind-hoare-while
organization: palmskog
community: false
action: true
coqdoc: false
dune: true
branch: abyss
doi: 10.2168/LMCS-11(1:1)2015

synopsis: >-
  Hoare logic in Coq for coinductive trace-based operational semantics of While

description: |-
  A Hoare logic in Coq for coinductive trace-based operational semantics for the
  While language, using predicative definitions of relations.

publications:
- pub_url: https://arxiv.org/abs/1412.6579
  pub_title: A Hoare logic for the coinductive trace-based big-step semantics of While
  pub_doi: 10.2168/LMCS-11(1:1)2015

authors:
- name: Keiko Nakata
  initial: true
- name: Tarmo Uustalu
  initial: true

opam-file-maintainer: palmskog@gmail.com

opam-file-version: dev

license:
  fullname: MIT License
  identifier: MIT

supported_coq_versions:
  text: 8.10 or later
  opam: '{>= "8.10"}'

tested_coq_opam_versions:
- version: 'dev'
- version: '8.17'
- version: '8.16'
- version: '8.15'
- version: '8.14'
- version: '8.13'
- version: '8.12'
- version: '8.11'
- version: '8.10'

namespace: CoindHoareWhile

keywords:
- name: coinduction
- name: while
- name: Hoare logic

categories:
- name: Computer Science/Semantics and Compilation/Semantics

build: |-
 ## Building instructions

 ``` shell
 git clone https://github.com/palmskog/coind-sem-while
 cd coind-sem-while
 git checkout abyss
 make   # or make -j <number-of-cores-on-your-machine>
 ```

documentation: |-
  ## Documentation

  - `Assert.v`: the assertion language and properties of the assertions
  - `Hoare.v`: the partial-correctness Hoare logic, embedding and projection
  - `HoareTotal.v`: the total-correctness Hoare logic, embedding and projection
  - `Semax.v`: the trace-based Hoare logic
  - `Markov.v`: corresponds to Section 5.1
  - `Liveness.v`: corresponds to Section 5.2
  - `Weakbism.v`: corresponds to Section 5.3
---
